/*
  # Expand NZ Suburbs

  Adds ~200 additional suburb entries to nz_locations covering:
  - Auckland (central, west, north shore, south)
  - Wellington city and Hutt Valley
  - Christchurch / Canterbury
  - Dunedin / Otago
  - Hamilton, Tauranga, Rotorua, Napier/Hastings
  - Palmerston North, New Plymouth, Nelson, Invercargill

  Uses ON CONFLICT DO NOTHING to safely skip any existing entries.
*/

INSERT INTO nz_locations (name, region, type) VALUES

-- ── AUCKLAND — Central ──────────────────────────────────────────────────
('St Heliers', 'Auckland', 'suburb'),
('Mission Bay', 'Auckland', 'suburb'),
('Kohimarama', 'Auckland', 'suburb'),
('Orakei', 'Auckland', 'suburb'),
('Glen Innes', 'Auckland', 'suburb'),
('Panmure', 'Auckland', 'suburb'),
('Point England', 'Auckland', 'suburb'),
('Meadowbank', 'Auckland', 'suburb'),
('St Johns', 'Auckland', 'suburb'),
('Ellerslie', 'Auckland', 'suburb'),
('Penrose', 'Auckland', 'suburb'),
('Greenlane', 'Auckland', 'suburb'),
('Royal Oak', 'Auckland', 'suburb'),
('Three Kings', 'Auckland', 'suburb'),
('Hillsborough', 'Auckland', 'suburb'),
('Lynfield', 'Auckland', 'suburb'),
('Blockhouse Bay', 'Auckland', 'suburb'),
('Green Bay', 'Auckland', 'suburb'),
('Kelston', 'Auckland', 'suburb'),
('Glendene', 'Auckland', 'suburb'),
('Te Atatu Peninsula', 'Auckland', 'suburb'),
('Te Atatu South', 'Auckland', 'suburb'),
('Massey', 'Auckland', 'suburb'),
('Royal Heights', 'Auckland', 'suburb'),
('Westgate', 'Auckland', 'suburb'),
('Ranui', 'Auckland', 'suburb'),
('Sunnyvale', 'Auckland', 'suburb'),
('Kingsland', 'Auckland', 'suburb'),
('Morningside', 'Auckland', 'suburb'),
('Sandringham', 'Auckland', 'suburb'),
('Balmoral', 'Auckland', 'suburb'),
('Mount Albert', 'Auckland', 'suburb'),
('Western Springs', 'Auckland', 'suburb'),
('Point Chevalier', 'Auckland', 'suburb'),
('Waterview', 'Auckland', 'suburb'),
('Grafton', 'Auckland', 'suburb'),
('Herne Bay', 'Auckland', 'suburb'),
('St Marys Bay', 'Auckland', 'suburb'),
('Freeman''s Bay', 'Auckland', 'suburb'),
('Eden Terrace', 'Auckland', 'suburb'),
('Arch Hill', 'Auckland', 'suburb'),

-- ── AUCKLAND — North Shore ───────────────────────────────────────────────
('Milford', 'Auckland', 'suburb'),
('Forrest Hill', 'Auckland', 'suburb'),
('Hillcrest', 'Auckland', 'suburb'),
('Northcote', 'Auckland', 'suburb'),
('Beach Haven', 'Auckland', 'suburb'),
('Birkdale', 'Auckland', 'suburb'),
('Browns Bay', 'Auckland', 'suburb'),
('Mairangi Bay', 'Auckland', 'suburb'),
('Torbay', 'Auckland', 'suburb'),
('Long Bay', 'Auckland', 'suburb'),
('Murrays Bay', 'Auckland', 'suburb'),
('Rothesay Bay', 'Auckland', 'suburb'),
('Windsor Park', 'Auckland', 'suburb'),
('Pinehill', 'Auckland', 'suburb'),
('Unsworth Heights', 'Auckland', 'suburb'),
('Totara Vale', 'Auckland', 'suburb'),
('Sunnynook', 'Auckland', 'suburb'),
('Campbells Bay', 'Auckland', 'suburb'),
('Castor Bay', 'Auckland', 'suburb'),
('Wairau Valley', 'Auckland', 'suburb'),
('Rosedale', 'Auckland', 'suburb'),

-- ── AUCKLAND — South ────────────────────────────────────────────────────
('Mangere', 'Auckland', 'suburb'),
('Mangere Bridge', 'Auckland', 'suburb'),
('Favona', 'Auckland', 'suburb'),
('Clendon Park', 'Auckland', 'suburb'),
('Wiri', 'Auckland', 'suburb'),
('Weymouth', 'Auckland', 'suburb'),
('Randwick Park', 'Auckland', 'suburb'),
('Conifer Grove', 'Auckland', 'suburb'),
('Takanini', 'Auckland', 'suburb'),
('Clover Park', 'Auckland', 'suburb'),
('Goodwood Heights', 'Auckland', 'suburb'),
('Karaka', 'Auckland', 'suburb'),

-- ── WELLINGTON CITY ──────────────────────────────────────────────────────
('Karori', 'Wellington', 'suburb'),
('Newtown', 'Wellington', 'suburb'),
('Island Bay', 'Wellington', 'suburb'),
('Brooklyn', 'Wellington', 'suburb'),
('Miramar', 'Wellington', 'suburb'),
('Kilbirnie', 'Wellington', 'suburb'),
('Hataitai', 'Wellington', 'suburb'),
('Rongotai', 'Wellington', 'suburb'),
('Strathmore Park', 'Wellington', 'suburb'),
('Berhampore', 'Wellington', 'suburb'),
('Seatoun', 'Wellington', 'suburb'),
('Lyall Bay', 'Wellington', 'suburb'),
('Te Aro', 'Wellington', 'suburb'),
('Mt Victoria', 'Wellington', 'suburb'),
('Thorndon', 'Wellington', 'suburb'),
('Kelburn', 'Wellington', 'suburb'),
('Wadestown', 'Wellington', 'suburb'),
('Northland', 'Wellington', 'suburb'),
('Khandallah', 'Wellington', 'suburb'),
('Ngaio', 'Wellington', 'suburb'),
('Crofton Downs', 'Wellington', 'suburb'),
('Newlands', 'Wellington', 'suburb'),
('Paparangi', 'Wellington', 'suburb'),
('Churton Park', 'Wellington', 'suburb'),
('Grenada Village', 'Wellington', 'suburb'),
('Glenside', 'Wellington', 'suburb'),
('Kaiwharawhara', 'Wellington', 'suburb'),
('Ngauranga', 'Wellington', 'suburb'),
('Makara', 'Wellington', 'suburb'),

-- ── WELLINGTON — Hutt Valley ─────────────────────────────────────────────
('Naenae', 'Wellington', 'suburb'),
('Stokes Valley', 'Wellington', 'suburb'),
('Wainuiomata', 'Wellington', 'suburb'),
('Taita', 'Wellington', 'suburb'),
('Avalon', 'Wellington', 'suburb'),
('Waterloo', 'Wellington', 'suburb'),
('Maungaraki', 'Wellington', 'suburb'),
('Woburn', 'Wellington', 'suburb'),
('Epuni', 'Wellington', 'suburb'),
('Manor Park', 'Wellington', 'suburb'),
('Birchville', 'Wellington', 'suburb'),

-- ── CHRISTCHURCH / CANTERBURY ────────────────────────────────────────────
('Riccarton', 'Canterbury', 'suburb'),
('Hornby', 'Canterbury', 'suburb'),
('Sockburn', 'Canterbury', 'suburb'),
('Wigram', 'Canterbury', 'suburb'),
('Halswell', 'Canterbury', 'suburb'),
('Cashmere', 'Canterbury', 'suburb'),
('Spreydon', 'Canterbury', 'suburb'),
('Sydenham', 'Canterbury', 'suburb'),
('Addington', 'Canterbury', 'suburb'),
('St Albans', 'Canterbury', 'suburb'),
('Merivale', 'Canterbury', 'suburb'),
('Fendalton', 'Canterbury', 'suburb'),
('Ilam', 'Canterbury', 'suburb'),
('Upper Riccarton', 'Canterbury', 'suburb'),
('Burnside', 'Canterbury', 'suburb'),
('Harewood', 'Canterbury', 'suburb'),
('Papanui', 'Canterbury', 'suburb'),
('Redwood', 'Canterbury', 'suburb'),
('Northwood', 'Canterbury', 'suburb'),
('New Brighton', 'Canterbury', 'suburb'),
('Sumner', 'Canterbury', 'suburb'),
('Lyttelton', 'Canterbury', 'suburb'),
('Shirley', 'Canterbury', 'suburb'),
('Bexley', 'Canterbury', 'suburb'),
('Aranui', 'Canterbury', 'suburb'),
('Bromley', 'Canterbury', 'suburb'),
('Wainoni', 'Canterbury', 'suburb'),
('Woolston', 'Canterbury', 'suburb'),
('Linwood', 'Canterbury', 'suburb'),
('Phillipstown', 'Canterbury', 'suburb'),
('Edgeware', 'Canterbury', 'suburb'),
('Mairehau', 'Canterbury', 'suburb'),
('Parklands', 'Canterbury', 'suburb'),
('Avonhead', 'Canterbury', 'suburb'),
('Russley', 'Canterbury', 'suburb'),
('Yaldhurst', 'Canterbury', 'suburb'),
('Islington', 'Canterbury', 'suburb'),
('Templeton', 'Canterbury', 'suburb'),

-- ── DUNEDIN / OTAGO ──────────────────────────────────────────────────────
('Caversham', 'Otago', 'suburb'),
('South Dunedin', 'Otago', 'suburb'),
('Brockville', 'Otago', 'suburb'),
('Corstorphine', 'Otago', 'suburb'),
('Green Island', 'Otago', 'suburb'),
('Abbotsford', 'Otago', 'suburb'),
('Halfway Bush', 'Otago', 'suburb'),
('Glenleith', 'Otago', 'suburb'),
('St Kilda', 'Otago', 'suburb'),
('St Clair', 'Otago', 'suburb'),
('Musselburgh', 'Otago', 'suburb'),
('Andersons Bay', 'Otago', 'suburb'),
('Mornington', 'Otago', 'suburb'),
('Kenmure', 'Otago', 'suburb'),
('Maori Hill', 'Otago', 'suburb'),
('Roslyn', 'Otago', 'suburb'),
('Wakari', 'Otago', 'suburb'),
('Helensburgh', 'Otago', 'suburb'),
('Pine Hill', 'Otago', 'suburb'),

-- ── HAMILTON / WAIKATO ───────────────────────────────────────────────────
('Dinsdale', 'Waikato', 'suburb'),
('Nawton', 'Waikato', 'suburb'),
('Frankton', 'Waikato', 'suburb'),
('Chartwell', 'Waikato', 'suburb'),
('Rototuna', 'Waikato', 'suburb'),
('Flagstaff', 'Waikato', 'suburb'),
('Temple View', 'Waikato', 'suburb'),
('Te Rapa', 'Waikato', 'suburb'),
('Claudelands', 'Waikato', 'suburb'),
('Enderley', 'Waikato', 'suburb'),
('Beerescourt', 'Waikato', 'suburb'),
('Melville', 'Waikato', 'suburb'),
('Forest Lake', 'Waikato', 'suburb'),
('Glenview', 'Waikato', 'suburb'),
('Riverlea', 'Waikato', 'suburb'),
('Maeroa', 'Waikato', 'suburb'),
('Hamilton Lake', 'Waikato', 'suburb'),
('Queenwood', 'Waikato', 'suburb'),
('Ruakura', 'Waikato', 'suburb'),

-- ── TAURANGA / BAY OF PLENTY ─────────────────────────────────────────────
('Greerton', 'Bay of Plenty', 'suburb'),
('Welcome Bay', 'Bay of Plenty', 'suburb'),
('Ohauiti', 'Bay of Plenty', 'suburb'),
('Matua', 'Bay of Plenty', 'suburb'),
('Bethlehem', 'Bay of Plenty', 'suburb'),
('Otumoetai', 'Bay of Plenty', 'suburb'),
('Brookfield', 'Bay of Plenty', 'suburb'),
('Pyes Pa', 'Bay of Plenty', 'suburb'),
('Hairini', 'Bay of Plenty', 'suburb'),
('Gate Pa', 'Bay of Plenty', 'suburb'),
('Parkvale', 'Bay of Plenty', 'suburb'),
('Judea', 'Bay of Plenty', 'suburb'),
('Bellevue', 'Bay of Plenty', 'suburb'),
('Arataki', 'Bay of Plenty', 'suburb'),

-- ── ROTORUA / BAY OF PLENTY ──────────────────────────────────────────────
('Ngongotaha', 'Bay of Plenty', 'suburb'),
('Holdens Bay', 'Bay of Plenty', 'suburb'),
('Glenholme', 'Bay of Plenty', 'suburb'),
('Fairy Springs', 'Bay of Plenty', 'suburb'),
('Fordlands', 'Bay of Plenty', 'suburb'),
('Koutu', 'Bay of Plenty', 'suburb'),
('Lynmore', 'Bay of Plenty', 'suburb'),
('Owhata', 'Bay of Plenty', 'suburb'),

-- ── NAPIER / HASTINGS — HAWKE''S BAY ─────────────────────────────────────
('Onekawa', 'Hawke''s Bay', 'suburb'),
('Marewa', 'Hawke''s Bay', 'suburb'),
('Taradale', 'Hawke''s Bay', 'suburb'),
('Flaxmere', 'Hawke''s Bay', 'suburb'),
('Mahora', 'Hawke''s Bay', 'suburb'),
('Camberley', 'Hawke''s Bay', 'suburb'),
('Clive', 'Hawke''s Bay', 'suburb'),
('Pirimai', 'Hawke''s Bay', 'suburb'),
('Maraenui', 'Hawke''s Bay', 'suburb'),
('Greenmeadows', 'Hawke''s Bay', 'suburb'),

-- ── PALMERSTON NORTH / MANAWATU ──────────────────────────────────────────
('Terrace End', 'Manawatu-Whanganui', 'suburb'),
('Fitzherbert', 'Manawatu-Whanganui', 'suburb'),
('Hokowhitu', 'Manawatu-Whanganui', 'suburb'),
('Kelvin Grove', 'Manawatu-Whanganui', 'suburb'),
('Awapuni', 'Manawatu-Whanganui', 'suburb'),
('Milson', 'Manawatu-Whanganui', 'suburb'),
('Takaro', 'Manawatu-Whanganui', 'suburb'),
('Cloverlea', 'Manawatu-Whanganui', 'suburb'),
('Highbury', 'Manawatu-Whanganui', 'suburb'),

-- ── NEW PLYMOUTH / TARANAKI ───────────────────────────────────────────────
('Strandon', 'Taranaki', 'suburb'),
('Vogeltown', 'Taranaki', 'suburb'),
('Brooklands', 'Taranaki', 'suburb'),
('Merrilands', 'Taranaki', 'suburb'),
('Moturoa', 'Taranaki', 'suburb'),
('Westown', 'Taranaki', 'suburb'),
('Blagdon', 'Taranaki', 'suburb'),
('Fitzroy', 'Taranaki', 'suburb'),
('Bell Block', 'Taranaki', 'suburb'),
('Spotswood', 'Taranaki', 'suburb'),

-- ── NELSON ───────────────────────────────────────────────────────────────
('Atawhai', 'Nelson', 'suburb'),
('Enner Glynn', 'Nelson', 'suburb'),
('Toi Toi', 'Nelson', 'suburb'),
('The Wood', 'Nelson', 'suburb'),
('Bishopdale', 'Nelson', 'suburb'),
('Tahunanui', 'Nelson', 'suburb'),

-- ── INVERCARGILL / SOUTHLAND ─────────────────────────────────────────────
('Waikiwi', 'Southland', 'suburb'),
('Kingswell', 'Southland', 'suburb'),
('Georgetown', 'Southland', 'suburb'),
('Grasmere', 'Southland', 'suburb'),
('Newfield', 'Southland', 'suburb'),
('Strathern', 'Southland', 'suburb'),
('Gladstone', 'Southland', 'suburb')

ON CONFLICT (name, region) DO NOTHING;
